// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fpgaconvnet_ip,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.562000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=42666,HLS_SYN_DSP=60960,HLS_SYN_FF=29962826,HLS_SYN_LUT=11416175,HLS_VERSION=2019_2}" *)

module fpgaconvnet_ip (
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_fpgaconvnet_port_wr_AWVALID,
        m_axi_fpgaconvnet_port_wr_AWREADY,
        m_axi_fpgaconvnet_port_wr_AWADDR,
        m_axi_fpgaconvnet_port_wr_AWID,
        m_axi_fpgaconvnet_port_wr_AWLEN,
        m_axi_fpgaconvnet_port_wr_AWSIZE,
        m_axi_fpgaconvnet_port_wr_AWBURST,
        m_axi_fpgaconvnet_port_wr_AWLOCK,
        m_axi_fpgaconvnet_port_wr_AWCACHE,
        m_axi_fpgaconvnet_port_wr_AWPROT,
        m_axi_fpgaconvnet_port_wr_AWQOS,
        m_axi_fpgaconvnet_port_wr_AWREGION,
        m_axi_fpgaconvnet_port_wr_AWUSER,
        m_axi_fpgaconvnet_port_wr_WVALID,
        m_axi_fpgaconvnet_port_wr_WREADY,
        m_axi_fpgaconvnet_port_wr_WDATA,
        m_axi_fpgaconvnet_port_wr_WSTRB,
        m_axi_fpgaconvnet_port_wr_WLAST,
        m_axi_fpgaconvnet_port_wr_WID,
        m_axi_fpgaconvnet_port_wr_WUSER,
        m_axi_fpgaconvnet_port_wr_ARVALID,
        m_axi_fpgaconvnet_port_wr_ARREADY,
        m_axi_fpgaconvnet_port_wr_ARADDR,
        m_axi_fpgaconvnet_port_wr_ARID,
        m_axi_fpgaconvnet_port_wr_ARLEN,
        m_axi_fpgaconvnet_port_wr_ARSIZE,
        m_axi_fpgaconvnet_port_wr_ARBURST,
        m_axi_fpgaconvnet_port_wr_ARLOCK,
        m_axi_fpgaconvnet_port_wr_ARCACHE,
        m_axi_fpgaconvnet_port_wr_ARPROT,
        m_axi_fpgaconvnet_port_wr_ARQOS,
        m_axi_fpgaconvnet_port_wr_ARREGION,
        m_axi_fpgaconvnet_port_wr_ARUSER,
        m_axi_fpgaconvnet_port_wr_RVALID,
        m_axi_fpgaconvnet_port_wr_RREADY,
        m_axi_fpgaconvnet_port_wr_RDATA,
        m_axi_fpgaconvnet_port_wr_RLAST,
        m_axi_fpgaconvnet_port_wr_RID,
        m_axi_fpgaconvnet_port_wr_RUSER,
        m_axi_fpgaconvnet_port_wr_RRESP,
        m_axi_fpgaconvnet_port_wr_BVALID,
        m_axi_fpgaconvnet_port_wr_BREADY,
        m_axi_fpgaconvnet_port_wr_BRESP,
        m_axi_fpgaconvnet_port_wr_BID,
        m_axi_fpgaconvnet_port_wr_BUSER,
        m_axi_fpgaconvnet_port_in_AWVALID,
        m_axi_fpgaconvnet_port_in_AWREADY,
        m_axi_fpgaconvnet_port_in_AWADDR,
        m_axi_fpgaconvnet_port_in_AWID,
        m_axi_fpgaconvnet_port_in_AWLEN,
        m_axi_fpgaconvnet_port_in_AWSIZE,
        m_axi_fpgaconvnet_port_in_AWBURST,
        m_axi_fpgaconvnet_port_in_AWLOCK,
        m_axi_fpgaconvnet_port_in_AWCACHE,
        m_axi_fpgaconvnet_port_in_AWPROT,
        m_axi_fpgaconvnet_port_in_AWQOS,
        m_axi_fpgaconvnet_port_in_AWREGION,
        m_axi_fpgaconvnet_port_in_AWUSER,
        m_axi_fpgaconvnet_port_in_WVALID,
        m_axi_fpgaconvnet_port_in_WREADY,
        m_axi_fpgaconvnet_port_in_WDATA,
        m_axi_fpgaconvnet_port_in_WSTRB,
        m_axi_fpgaconvnet_port_in_WLAST,
        m_axi_fpgaconvnet_port_in_WID,
        m_axi_fpgaconvnet_port_in_WUSER,
        m_axi_fpgaconvnet_port_in_ARVALID,
        m_axi_fpgaconvnet_port_in_ARREADY,
        m_axi_fpgaconvnet_port_in_ARADDR,
        m_axi_fpgaconvnet_port_in_ARID,
        m_axi_fpgaconvnet_port_in_ARLEN,
        m_axi_fpgaconvnet_port_in_ARSIZE,
        m_axi_fpgaconvnet_port_in_ARBURST,
        m_axi_fpgaconvnet_port_in_ARLOCK,
        m_axi_fpgaconvnet_port_in_ARCACHE,
        m_axi_fpgaconvnet_port_in_ARPROT,
        m_axi_fpgaconvnet_port_in_ARQOS,
        m_axi_fpgaconvnet_port_in_ARREGION,
        m_axi_fpgaconvnet_port_in_ARUSER,
        m_axi_fpgaconvnet_port_in_RVALID,
        m_axi_fpgaconvnet_port_in_RREADY,
        m_axi_fpgaconvnet_port_in_RDATA,
        m_axi_fpgaconvnet_port_in_RLAST,
        m_axi_fpgaconvnet_port_in_RID,
        m_axi_fpgaconvnet_port_in_RUSER,
        m_axi_fpgaconvnet_port_in_RRESP,
        m_axi_fpgaconvnet_port_in_BVALID,
        m_axi_fpgaconvnet_port_in_BREADY,
        m_axi_fpgaconvnet_port_in_BRESP,
        m_axi_fpgaconvnet_port_in_BID,
        m_axi_fpgaconvnet_port_in_BUSER,
        m_axi_fpgaconvnet_port_out_AWVALID,
        m_axi_fpgaconvnet_port_out_AWREADY,
        m_axi_fpgaconvnet_port_out_AWADDR,
        m_axi_fpgaconvnet_port_out_AWID,
        m_axi_fpgaconvnet_port_out_AWLEN,
        m_axi_fpgaconvnet_port_out_AWSIZE,
        m_axi_fpgaconvnet_port_out_AWBURST,
        m_axi_fpgaconvnet_port_out_AWLOCK,
        m_axi_fpgaconvnet_port_out_AWCACHE,
        m_axi_fpgaconvnet_port_out_AWPROT,
        m_axi_fpgaconvnet_port_out_AWQOS,
        m_axi_fpgaconvnet_port_out_AWREGION,
        m_axi_fpgaconvnet_port_out_AWUSER,
        m_axi_fpgaconvnet_port_out_WVALID,
        m_axi_fpgaconvnet_port_out_WREADY,
        m_axi_fpgaconvnet_port_out_WDATA,
        m_axi_fpgaconvnet_port_out_WSTRB,
        m_axi_fpgaconvnet_port_out_WLAST,
        m_axi_fpgaconvnet_port_out_WID,
        m_axi_fpgaconvnet_port_out_WUSER,
        m_axi_fpgaconvnet_port_out_ARVALID,
        m_axi_fpgaconvnet_port_out_ARREADY,
        m_axi_fpgaconvnet_port_out_ARADDR,
        m_axi_fpgaconvnet_port_out_ARID,
        m_axi_fpgaconvnet_port_out_ARLEN,
        m_axi_fpgaconvnet_port_out_ARSIZE,
        m_axi_fpgaconvnet_port_out_ARBURST,
        m_axi_fpgaconvnet_port_out_ARLOCK,
        m_axi_fpgaconvnet_port_out_ARCACHE,
        m_axi_fpgaconvnet_port_out_ARPROT,
        m_axi_fpgaconvnet_port_out_ARQOS,
        m_axi_fpgaconvnet_port_out_ARREGION,
        m_axi_fpgaconvnet_port_out_ARUSER,
        m_axi_fpgaconvnet_port_out_RVALID,
        m_axi_fpgaconvnet_port_out_RREADY,
        m_axi_fpgaconvnet_port_out_RDATA,
        m_axi_fpgaconvnet_port_out_RLAST,
        m_axi_fpgaconvnet_port_out_RID,
        m_axi_fpgaconvnet_port_out_RUSER,
        m_axi_fpgaconvnet_port_out_RRESP,
        m_axi_fpgaconvnet_port_out_BVALID,
        m_axi_fpgaconvnet_port_out_BREADY,
        m_axi_fpgaconvnet_port_out_BRESP,
        m_axi_fpgaconvnet_port_out_BID,
        m_axi_fpgaconvnet_port_out_BUSER
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_ADDR_WIDTH = 32;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_DATA_WIDTH = 64;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_WUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_RUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_BUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_USER_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_PROT_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_WR_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_ADDR_WIDTH = 32;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_DATA_WIDTH = 64;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_WUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_RUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_BUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_USER_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_PROT_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_IN_CACHE_VALUE = 3;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_ADDR_WIDTH = 32;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_DATA_WIDTH = 64;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_USER_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_FPGACONVNET_PORT_OUT_CACHE_VALUE = 3;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_FPGACONVNET_PORT_WR_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_FPGACONVNET_PORT_IN_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_FPGACONVNET_PORT_OUT_WSTRB_WIDTH = (64 / 8);

input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_fpgaconvnet_port_wr_AWVALID;
input   m_axi_fpgaconvnet_port_wr_AWREADY;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_AWADDR;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_AWID;
output  [7:0] m_axi_fpgaconvnet_port_wr_AWLEN;
output  [2:0] m_axi_fpgaconvnet_port_wr_AWSIZE;
output  [1:0] m_axi_fpgaconvnet_port_wr_AWBURST;
output  [1:0] m_axi_fpgaconvnet_port_wr_AWLOCK;
output  [3:0] m_axi_fpgaconvnet_port_wr_AWCACHE;
output  [2:0] m_axi_fpgaconvnet_port_wr_AWPROT;
output  [3:0] m_axi_fpgaconvnet_port_wr_AWQOS;
output  [3:0] m_axi_fpgaconvnet_port_wr_AWREGION;
output  [C_M_AXI_FPGACONVNET_PORT_WR_AWUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_AWUSER;
output   m_axi_fpgaconvnet_port_wr_WVALID;
input   m_axi_fpgaconvnet_port_wr_WREADY;
output  [C_M_AXI_FPGACONVNET_PORT_WR_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_WDATA;
output  [C_M_AXI_FPGACONVNET_PORT_WR_WSTRB_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_WSTRB;
output   m_axi_fpgaconvnet_port_wr_WLAST;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_WID;
output  [C_M_AXI_FPGACONVNET_PORT_WR_WUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_WUSER;
output   m_axi_fpgaconvnet_port_wr_ARVALID;
input   m_axi_fpgaconvnet_port_wr_ARREADY;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_ARADDR;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_ARID;
output  [7:0] m_axi_fpgaconvnet_port_wr_ARLEN;
output  [2:0] m_axi_fpgaconvnet_port_wr_ARSIZE;
output  [1:0] m_axi_fpgaconvnet_port_wr_ARBURST;
output  [1:0] m_axi_fpgaconvnet_port_wr_ARLOCK;
output  [3:0] m_axi_fpgaconvnet_port_wr_ARCACHE;
output  [2:0] m_axi_fpgaconvnet_port_wr_ARPROT;
output  [3:0] m_axi_fpgaconvnet_port_wr_ARQOS;
output  [3:0] m_axi_fpgaconvnet_port_wr_ARREGION;
output  [C_M_AXI_FPGACONVNET_PORT_WR_ARUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_ARUSER;
input   m_axi_fpgaconvnet_port_wr_RVALID;
output   m_axi_fpgaconvnet_port_wr_RREADY;
input  [C_M_AXI_FPGACONVNET_PORT_WR_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_RDATA;
input   m_axi_fpgaconvnet_port_wr_RLAST;
input  [C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_RID;
input  [C_M_AXI_FPGACONVNET_PORT_WR_RUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_RUSER;
input  [1:0] m_axi_fpgaconvnet_port_wr_RRESP;
input   m_axi_fpgaconvnet_port_wr_BVALID;
output   m_axi_fpgaconvnet_port_wr_BREADY;
input  [1:0] m_axi_fpgaconvnet_port_wr_BRESP;
input  [C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_BID;
input  [C_M_AXI_FPGACONVNET_PORT_WR_BUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_wr_BUSER;
output   m_axi_fpgaconvnet_port_in_AWVALID;
input   m_axi_fpgaconvnet_port_in_AWREADY;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_AWADDR;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_AWID;
output  [7:0] m_axi_fpgaconvnet_port_in_AWLEN;
output  [2:0] m_axi_fpgaconvnet_port_in_AWSIZE;
output  [1:0] m_axi_fpgaconvnet_port_in_AWBURST;
output  [1:0] m_axi_fpgaconvnet_port_in_AWLOCK;
output  [3:0] m_axi_fpgaconvnet_port_in_AWCACHE;
output  [2:0] m_axi_fpgaconvnet_port_in_AWPROT;
output  [3:0] m_axi_fpgaconvnet_port_in_AWQOS;
output  [3:0] m_axi_fpgaconvnet_port_in_AWREGION;
output  [C_M_AXI_FPGACONVNET_PORT_IN_AWUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_AWUSER;
output   m_axi_fpgaconvnet_port_in_WVALID;
input   m_axi_fpgaconvnet_port_in_WREADY;
output  [C_M_AXI_FPGACONVNET_PORT_IN_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_WDATA;
output  [C_M_AXI_FPGACONVNET_PORT_IN_WSTRB_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_WSTRB;
output   m_axi_fpgaconvnet_port_in_WLAST;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_WID;
output  [C_M_AXI_FPGACONVNET_PORT_IN_WUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_WUSER;
output   m_axi_fpgaconvnet_port_in_ARVALID;
input   m_axi_fpgaconvnet_port_in_ARREADY;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_ARADDR;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_ARID;
output  [7:0] m_axi_fpgaconvnet_port_in_ARLEN;
output  [2:0] m_axi_fpgaconvnet_port_in_ARSIZE;
output  [1:0] m_axi_fpgaconvnet_port_in_ARBURST;
output  [1:0] m_axi_fpgaconvnet_port_in_ARLOCK;
output  [3:0] m_axi_fpgaconvnet_port_in_ARCACHE;
output  [2:0] m_axi_fpgaconvnet_port_in_ARPROT;
output  [3:0] m_axi_fpgaconvnet_port_in_ARQOS;
output  [3:0] m_axi_fpgaconvnet_port_in_ARREGION;
output  [C_M_AXI_FPGACONVNET_PORT_IN_ARUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_ARUSER;
input   m_axi_fpgaconvnet_port_in_RVALID;
output   m_axi_fpgaconvnet_port_in_RREADY;
input  [C_M_AXI_FPGACONVNET_PORT_IN_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_RDATA;
input   m_axi_fpgaconvnet_port_in_RLAST;
input  [C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_RID;
input  [C_M_AXI_FPGACONVNET_PORT_IN_RUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_RUSER;
input  [1:0] m_axi_fpgaconvnet_port_in_RRESP;
input   m_axi_fpgaconvnet_port_in_BVALID;
output   m_axi_fpgaconvnet_port_in_BREADY;
input  [1:0] m_axi_fpgaconvnet_port_in_BRESP;
input  [C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_BID;
input  [C_M_AXI_FPGACONVNET_PORT_IN_BUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_in_BUSER;
output   m_axi_fpgaconvnet_port_out_AWVALID;
input   m_axi_fpgaconvnet_port_out_AWREADY;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_AWADDR;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_AWID;
output  [7:0] m_axi_fpgaconvnet_port_out_AWLEN;
output  [2:0] m_axi_fpgaconvnet_port_out_AWSIZE;
output  [1:0] m_axi_fpgaconvnet_port_out_AWBURST;
output  [1:0] m_axi_fpgaconvnet_port_out_AWLOCK;
output  [3:0] m_axi_fpgaconvnet_port_out_AWCACHE;
output  [2:0] m_axi_fpgaconvnet_port_out_AWPROT;
output  [3:0] m_axi_fpgaconvnet_port_out_AWQOS;
output  [3:0] m_axi_fpgaconvnet_port_out_AWREGION;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_AWUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_AWUSER;
output   m_axi_fpgaconvnet_port_out_WVALID;
input   m_axi_fpgaconvnet_port_out_WREADY;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_WDATA;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_WSTRB_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_WSTRB;
output   m_axi_fpgaconvnet_port_out_WLAST;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_WID;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_WUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_WUSER;
output   m_axi_fpgaconvnet_port_out_ARVALID;
input   m_axi_fpgaconvnet_port_out_ARREADY;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ADDR_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_ARADDR;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_ARID;
output  [7:0] m_axi_fpgaconvnet_port_out_ARLEN;
output  [2:0] m_axi_fpgaconvnet_port_out_ARSIZE;
output  [1:0] m_axi_fpgaconvnet_port_out_ARBURST;
output  [1:0] m_axi_fpgaconvnet_port_out_ARLOCK;
output  [3:0] m_axi_fpgaconvnet_port_out_ARCACHE;
output  [2:0] m_axi_fpgaconvnet_port_out_ARPROT;
output  [3:0] m_axi_fpgaconvnet_port_out_ARQOS;
output  [3:0] m_axi_fpgaconvnet_port_out_ARREGION;
output  [C_M_AXI_FPGACONVNET_PORT_OUT_ARUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_ARUSER;
input   m_axi_fpgaconvnet_port_out_RVALID;
output   m_axi_fpgaconvnet_port_out_RREADY;
input  [C_M_AXI_FPGACONVNET_PORT_OUT_DATA_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_RDATA;
input   m_axi_fpgaconvnet_port_out_RLAST;
input  [C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_RID;
input  [C_M_AXI_FPGACONVNET_PORT_OUT_RUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_RUSER;
input  [1:0] m_axi_fpgaconvnet_port_out_RRESP;
input   m_axi_fpgaconvnet_port_out_BVALID;
output   m_axi_fpgaconvnet_port_out_BREADY;
input  [1:0] m_axi_fpgaconvnet_port_out_BRESP;
input  [C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_BID;
input  [C_M_AXI_FPGACONVNET_PORT_OUT_BUSER_WIDTH - 1:0] m_axi_fpgaconvnet_port_out_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] mode;
wire   [31:0] weights_reloading_index;
wire   [31:0] fpgaconvnet_wr_0_V;
wire   [31:0] fpgaconvnet_in_0_V;
wire   [31:0] fpgaconvnet_out_0_V;
wire    fpgaconvnet_port_wr_AWREADY;
wire    fpgaconvnet_port_wr_WREADY;
wire    fpgaconvnet_port_wr_ARREADY;
wire    fpgaconvnet_port_wr_RVALID;
wire   [63:0] fpgaconvnet_port_wr_RDATA;
wire    fpgaconvnet_port_wr_RLAST;
wire   [0:0] fpgaconvnet_port_wr_RID;
wire   [0:0] fpgaconvnet_port_wr_RUSER;
wire   [1:0] fpgaconvnet_port_wr_RRESP;
wire    fpgaconvnet_port_wr_BVALID;
wire   [1:0] fpgaconvnet_port_wr_BRESP;
wire   [0:0] fpgaconvnet_port_wr_BID;
wire   [0:0] fpgaconvnet_port_wr_BUSER;
wire    fpgaconvnet_port_in_AWREADY;
wire    fpgaconvnet_port_in_WREADY;
wire    fpgaconvnet_port_in_ARREADY;
wire    fpgaconvnet_port_in_RVALID;
wire   [63:0] fpgaconvnet_port_in_RDATA;
wire    fpgaconvnet_port_in_RLAST;
wire   [0:0] fpgaconvnet_port_in_RID;
wire   [0:0] fpgaconvnet_port_in_RUSER;
wire   [1:0] fpgaconvnet_port_in_RRESP;
wire    fpgaconvnet_port_in_BVALID;
wire   [1:0] fpgaconvnet_port_in_BRESP;
wire   [0:0] fpgaconvnet_port_in_BID;
wire   [0:0] fpgaconvnet_port_in_BUSER;
wire    fpgaconvnet_port_out_AWREADY;
wire    fpgaconvnet_port_out_WREADY;
wire    fpgaconvnet_port_out_ARREADY;
wire    fpgaconvnet_port_out_RVALID;
wire   [63:0] fpgaconvnet_port_out_RDATA;
wire    fpgaconvnet_port_out_RLAST;
wire   [0:0] fpgaconvnet_port_out_RID;
wire   [0:0] fpgaconvnet_port_out_RUSER;
wire   [1:0] fpgaconvnet_port_out_RRESP;
wire    fpgaconvnet_port_out_BVALID;
wire   [1:0] fpgaconvnet_port_out_BRESP;
wire   [0:0] fpgaconvnet_port_out_BID;
wire   [0:0] fpgaconvnet_port_out_BUSER;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WVALID;
wire   [63:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WDATA;
wire   [7:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WSTRB;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WLAST;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WID;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_RREADY;
wire    Block_proc_U0_m_axi_fpgaconvnet_in_0_V_BREADY;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WVALID;
wire   [63:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WDATA;
wire   [7:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WSTRB;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WLAST;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WID;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_RREADY;
wire    Block_proc_U0_m_axi_fpgaconvnet_out_0_V_BREADY;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WVALID;
wire   [63:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WDATA;
wire   [7:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WSTRB;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WLAST;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WID;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARVALID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARADDR;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARID;
wire   [31:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLEN;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARSIZE;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARBURST;
wire   [1:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLOCK;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARCACHE;
wire   [2:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARPROT;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARQOS;
wire   [3:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARREGION;
wire   [0:0] Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARUSER;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_RREADY;
wire    Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_BREADY;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;

fpgaconvnet_ip_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
fpgaconvnet_ip_ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .mode(mode),
    .weights_reloading_index(weights_reloading_index),
    .fpgaconvnet_wr_0_V(fpgaconvnet_wr_0_V),
    .fpgaconvnet_in_0_V(fpgaconvnet_in_0_V),
    .fpgaconvnet_out_0_V(fpgaconvnet_out_0_V)
);

fpgaconvnet_ip_fpgaconvnet_port_wr_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 256 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_WR_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FPGACONVNET_PORT_WR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FPGACONVNET_PORT_WR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FPGACONVNET_PORT_WR_CACHE_VALUE ))
fpgaconvnet_ip_fpgaconvnet_port_wr_m_axi_U(
    .AWVALID(m_axi_fpgaconvnet_port_wr_AWVALID),
    .AWREADY(m_axi_fpgaconvnet_port_wr_AWREADY),
    .AWADDR(m_axi_fpgaconvnet_port_wr_AWADDR),
    .AWID(m_axi_fpgaconvnet_port_wr_AWID),
    .AWLEN(m_axi_fpgaconvnet_port_wr_AWLEN),
    .AWSIZE(m_axi_fpgaconvnet_port_wr_AWSIZE),
    .AWBURST(m_axi_fpgaconvnet_port_wr_AWBURST),
    .AWLOCK(m_axi_fpgaconvnet_port_wr_AWLOCK),
    .AWCACHE(m_axi_fpgaconvnet_port_wr_AWCACHE),
    .AWPROT(m_axi_fpgaconvnet_port_wr_AWPROT),
    .AWQOS(m_axi_fpgaconvnet_port_wr_AWQOS),
    .AWREGION(m_axi_fpgaconvnet_port_wr_AWREGION),
    .AWUSER(m_axi_fpgaconvnet_port_wr_AWUSER),
    .WVALID(m_axi_fpgaconvnet_port_wr_WVALID),
    .WREADY(m_axi_fpgaconvnet_port_wr_WREADY),
    .WDATA(m_axi_fpgaconvnet_port_wr_WDATA),
    .WSTRB(m_axi_fpgaconvnet_port_wr_WSTRB),
    .WLAST(m_axi_fpgaconvnet_port_wr_WLAST),
    .WID(m_axi_fpgaconvnet_port_wr_WID),
    .WUSER(m_axi_fpgaconvnet_port_wr_WUSER),
    .ARVALID(m_axi_fpgaconvnet_port_wr_ARVALID),
    .ARREADY(m_axi_fpgaconvnet_port_wr_ARREADY),
    .ARADDR(m_axi_fpgaconvnet_port_wr_ARADDR),
    .ARID(m_axi_fpgaconvnet_port_wr_ARID),
    .ARLEN(m_axi_fpgaconvnet_port_wr_ARLEN),
    .ARSIZE(m_axi_fpgaconvnet_port_wr_ARSIZE),
    .ARBURST(m_axi_fpgaconvnet_port_wr_ARBURST),
    .ARLOCK(m_axi_fpgaconvnet_port_wr_ARLOCK),
    .ARCACHE(m_axi_fpgaconvnet_port_wr_ARCACHE),
    .ARPROT(m_axi_fpgaconvnet_port_wr_ARPROT),
    .ARQOS(m_axi_fpgaconvnet_port_wr_ARQOS),
    .ARREGION(m_axi_fpgaconvnet_port_wr_ARREGION),
    .ARUSER(m_axi_fpgaconvnet_port_wr_ARUSER),
    .RVALID(m_axi_fpgaconvnet_port_wr_RVALID),
    .RREADY(m_axi_fpgaconvnet_port_wr_RREADY),
    .RDATA(m_axi_fpgaconvnet_port_wr_RDATA),
    .RLAST(m_axi_fpgaconvnet_port_wr_RLAST),
    .RID(m_axi_fpgaconvnet_port_wr_RID),
    .RUSER(m_axi_fpgaconvnet_port_wr_RUSER),
    .RRESP(m_axi_fpgaconvnet_port_wr_RRESP),
    .BVALID(m_axi_fpgaconvnet_port_wr_BVALID),
    .BREADY(m_axi_fpgaconvnet_port_wr_BREADY),
    .BRESP(m_axi_fpgaconvnet_port_wr_BRESP),
    .BID(m_axi_fpgaconvnet_port_wr_BID),
    .BUSER(m_axi_fpgaconvnet_port_wr_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARVALID),
    .I_ARREADY(fpgaconvnet_port_wr_ARREADY),
    .I_ARADDR(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARADDR),
    .I_ARID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARID),
    .I_ARLEN(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLEN),
    .I_ARSIZE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARSIZE),
    .I_ARLOCK(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLOCK),
    .I_ARCACHE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARCACHE),
    .I_ARQOS(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARQOS),
    .I_ARPROT(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARPROT),
    .I_ARUSER(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARUSER),
    .I_ARBURST(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARBURST),
    .I_ARREGION(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARREGION),
    .I_RVALID(fpgaconvnet_port_wr_RVALID),
    .I_RREADY(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_RREADY),
    .I_RDATA(fpgaconvnet_port_wr_RDATA),
    .I_RID(fpgaconvnet_port_wr_RID),
    .I_RUSER(fpgaconvnet_port_wr_RUSER),
    .I_RRESP(fpgaconvnet_port_wr_RRESP),
    .I_RLAST(fpgaconvnet_port_wr_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(fpgaconvnet_port_wr_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(fpgaconvnet_port_wr_WREADY),
    .I_WDATA(64'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(8'd0),
    .I_BVALID(fpgaconvnet_port_wr_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(fpgaconvnet_port_wr_BRESP),
    .I_BID(fpgaconvnet_port_wr_BID),
    .I_BUSER(fpgaconvnet_port_wr_BUSER)
);

fpgaconvnet_ip_fpgaconvnet_port_in_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 256 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_IN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FPGACONVNET_PORT_IN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FPGACONVNET_PORT_IN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FPGACONVNET_PORT_IN_CACHE_VALUE ))
fpgaconvnet_ip_fpgaconvnet_port_in_m_axi_U(
    .AWVALID(m_axi_fpgaconvnet_port_in_AWVALID),
    .AWREADY(m_axi_fpgaconvnet_port_in_AWREADY),
    .AWADDR(m_axi_fpgaconvnet_port_in_AWADDR),
    .AWID(m_axi_fpgaconvnet_port_in_AWID),
    .AWLEN(m_axi_fpgaconvnet_port_in_AWLEN),
    .AWSIZE(m_axi_fpgaconvnet_port_in_AWSIZE),
    .AWBURST(m_axi_fpgaconvnet_port_in_AWBURST),
    .AWLOCK(m_axi_fpgaconvnet_port_in_AWLOCK),
    .AWCACHE(m_axi_fpgaconvnet_port_in_AWCACHE),
    .AWPROT(m_axi_fpgaconvnet_port_in_AWPROT),
    .AWQOS(m_axi_fpgaconvnet_port_in_AWQOS),
    .AWREGION(m_axi_fpgaconvnet_port_in_AWREGION),
    .AWUSER(m_axi_fpgaconvnet_port_in_AWUSER),
    .WVALID(m_axi_fpgaconvnet_port_in_WVALID),
    .WREADY(m_axi_fpgaconvnet_port_in_WREADY),
    .WDATA(m_axi_fpgaconvnet_port_in_WDATA),
    .WSTRB(m_axi_fpgaconvnet_port_in_WSTRB),
    .WLAST(m_axi_fpgaconvnet_port_in_WLAST),
    .WID(m_axi_fpgaconvnet_port_in_WID),
    .WUSER(m_axi_fpgaconvnet_port_in_WUSER),
    .ARVALID(m_axi_fpgaconvnet_port_in_ARVALID),
    .ARREADY(m_axi_fpgaconvnet_port_in_ARREADY),
    .ARADDR(m_axi_fpgaconvnet_port_in_ARADDR),
    .ARID(m_axi_fpgaconvnet_port_in_ARID),
    .ARLEN(m_axi_fpgaconvnet_port_in_ARLEN),
    .ARSIZE(m_axi_fpgaconvnet_port_in_ARSIZE),
    .ARBURST(m_axi_fpgaconvnet_port_in_ARBURST),
    .ARLOCK(m_axi_fpgaconvnet_port_in_ARLOCK),
    .ARCACHE(m_axi_fpgaconvnet_port_in_ARCACHE),
    .ARPROT(m_axi_fpgaconvnet_port_in_ARPROT),
    .ARQOS(m_axi_fpgaconvnet_port_in_ARQOS),
    .ARREGION(m_axi_fpgaconvnet_port_in_ARREGION),
    .ARUSER(m_axi_fpgaconvnet_port_in_ARUSER),
    .RVALID(m_axi_fpgaconvnet_port_in_RVALID),
    .RREADY(m_axi_fpgaconvnet_port_in_RREADY),
    .RDATA(m_axi_fpgaconvnet_port_in_RDATA),
    .RLAST(m_axi_fpgaconvnet_port_in_RLAST),
    .RID(m_axi_fpgaconvnet_port_in_RID),
    .RUSER(m_axi_fpgaconvnet_port_in_RUSER),
    .RRESP(m_axi_fpgaconvnet_port_in_RRESP),
    .BVALID(m_axi_fpgaconvnet_port_in_BVALID),
    .BREADY(m_axi_fpgaconvnet_port_in_BREADY),
    .BRESP(m_axi_fpgaconvnet_port_in_BRESP),
    .BID(m_axi_fpgaconvnet_port_in_BID),
    .BUSER(m_axi_fpgaconvnet_port_in_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARVALID),
    .I_ARREADY(fpgaconvnet_port_in_ARREADY),
    .I_ARADDR(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARADDR),
    .I_ARID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARID),
    .I_ARLEN(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLEN),
    .I_ARSIZE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARSIZE),
    .I_ARLOCK(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLOCK),
    .I_ARCACHE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARCACHE),
    .I_ARQOS(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARQOS),
    .I_ARPROT(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARPROT),
    .I_ARUSER(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARUSER),
    .I_ARBURST(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARBURST),
    .I_ARREGION(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARREGION),
    .I_RVALID(fpgaconvnet_port_in_RVALID),
    .I_RREADY(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_RREADY),
    .I_RDATA(fpgaconvnet_port_in_RDATA),
    .I_RID(fpgaconvnet_port_in_RID),
    .I_RUSER(fpgaconvnet_port_in_RUSER),
    .I_RRESP(fpgaconvnet_port_in_RRESP),
    .I_RLAST(fpgaconvnet_port_in_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(fpgaconvnet_port_in_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(fpgaconvnet_port_in_WREADY),
    .I_WDATA(64'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(8'd0),
    .I_BVALID(fpgaconvnet_port_in_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(fpgaconvnet_port_in_BRESP),
    .I_BID(fpgaconvnet_port_in_BID),
    .I_BUSER(fpgaconvnet_port_in_BUSER)
);

fpgaconvnet_ip_fpgaconvnet_port_out_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 64 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 1 ),
    .NUM_WRITE_OUTSTANDING( 1 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 256 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FPGACONVNET_PORT_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FPGACONVNET_PORT_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FPGACONVNET_PORT_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FPGACONVNET_PORT_OUT_CACHE_VALUE ))
fpgaconvnet_ip_fpgaconvnet_port_out_m_axi_U(
    .AWVALID(m_axi_fpgaconvnet_port_out_AWVALID),
    .AWREADY(m_axi_fpgaconvnet_port_out_AWREADY),
    .AWADDR(m_axi_fpgaconvnet_port_out_AWADDR),
    .AWID(m_axi_fpgaconvnet_port_out_AWID),
    .AWLEN(m_axi_fpgaconvnet_port_out_AWLEN),
    .AWSIZE(m_axi_fpgaconvnet_port_out_AWSIZE),
    .AWBURST(m_axi_fpgaconvnet_port_out_AWBURST),
    .AWLOCK(m_axi_fpgaconvnet_port_out_AWLOCK),
    .AWCACHE(m_axi_fpgaconvnet_port_out_AWCACHE),
    .AWPROT(m_axi_fpgaconvnet_port_out_AWPROT),
    .AWQOS(m_axi_fpgaconvnet_port_out_AWQOS),
    .AWREGION(m_axi_fpgaconvnet_port_out_AWREGION),
    .AWUSER(m_axi_fpgaconvnet_port_out_AWUSER),
    .WVALID(m_axi_fpgaconvnet_port_out_WVALID),
    .WREADY(m_axi_fpgaconvnet_port_out_WREADY),
    .WDATA(m_axi_fpgaconvnet_port_out_WDATA),
    .WSTRB(m_axi_fpgaconvnet_port_out_WSTRB),
    .WLAST(m_axi_fpgaconvnet_port_out_WLAST),
    .WID(m_axi_fpgaconvnet_port_out_WID),
    .WUSER(m_axi_fpgaconvnet_port_out_WUSER),
    .ARVALID(m_axi_fpgaconvnet_port_out_ARVALID),
    .ARREADY(m_axi_fpgaconvnet_port_out_ARREADY),
    .ARADDR(m_axi_fpgaconvnet_port_out_ARADDR),
    .ARID(m_axi_fpgaconvnet_port_out_ARID),
    .ARLEN(m_axi_fpgaconvnet_port_out_ARLEN),
    .ARSIZE(m_axi_fpgaconvnet_port_out_ARSIZE),
    .ARBURST(m_axi_fpgaconvnet_port_out_ARBURST),
    .ARLOCK(m_axi_fpgaconvnet_port_out_ARLOCK),
    .ARCACHE(m_axi_fpgaconvnet_port_out_ARCACHE),
    .ARPROT(m_axi_fpgaconvnet_port_out_ARPROT),
    .ARQOS(m_axi_fpgaconvnet_port_out_ARQOS),
    .ARREGION(m_axi_fpgaconvnet_port_out_ARREGION),
    .ARUSER(m_axi_fpgaconvnet_port_out_ARUSER),
    .RVALID(m_axi_fpgaconvnet_port_out_RVALID),
    .RREADY(m_axi_fpgaconvnet_port_out_RREADY),
    .RDATA(m_axi_fpgaconvnet_port_out_RDATA),
    .RLAST(m_axi_fpgaconvnet_port_out_RLAST),
    .RID(m_axi_fpgaconvnet_port_out_RID),
    .RUSER(m_axi_fpgaconvnet_port_out_RUSER),
    .RRESP(m_axi_fpgaconvnet_port_out_RRESP),
    .BVALID(m_axi_fpgaconvnet_port_out_BVALID),
    .BREADY(m_axi_fpgaconvnet_port_out_BREADY),
    .BRESP(m_axi_fpgaconvnet_port_out_BRESP),
    .BID(m_axi_fpgaconvnet_port_out_BID),
    .BUSER(m_axi_fpgaconvnet_port_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(fpgaconvnet_port_out_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(fpgaconvnet_port_out_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(fpgaconvnet_port_out_RDATA),
    .I_RID(fpgaconvnet_port_out_RID),
    .I_RUSER(fpgaconvnet_port_out_RUSER),
    .I_RRESP(fpgaconvnet_port_out_RRESP),
    .I_RLAST(fpgaconvnet_port_out_RLAST),
    .I_AWVALID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWVALID),
    .I_AWREADY(fpgaconvnet_port_out_AWREADY),
    .I_AWADDR(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWADDR),
    .I_AWID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWID),
    .I_AWLEN(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLEN),
    .I_AWSIZE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWSIZE),
    .I_AWLOCK(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLOCK),
    .I_AWCACHE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWCACHE),
    .I_AWQOS(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWQOS),
    .I_AWPROT(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWPROT),
    .I_AWUSER(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWUSER),
    .I_AWBURST(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWBURST),
    .I_AWREGION(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWREGION),
    .I_WVALID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WVALID),
    .I_WREADY(fpgaconvnet_port_out_WREADY),
    .I_WDATA(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WDATA),
    .I_WID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WID),
    .I_WUSER(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WUSER),
    .I_WLAST(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WLAST),
    .I_WSTRB(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WSTRB),
    .I_BVALID(fpgaconvnet_port_out_BVALID),
    .I_BREADY(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_BREADY),
    .I_BRESP(fpgaconvnet_port_out_BRESP),
    .I_BID(fpgaconvnet_port_out_BID),
    .I_BUSER(fpgaconvnet_port_out_BUSER)
);

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .mode(mode),
    .weights_reloading_index(weights_reloading_index),
    .m_axi_fpgaconvnet_in_0_V_AWVALID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWVALID),
    .m_axi_fpgaconvnet_in_0_V_AWREADY(1'b0),
    .m_axi_fpgaconvnet_in_0_V_AWADDR(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWADDR),
    .m_axi_fpgaconvnet_in_0_V_AWID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWID),
    .m_axi_fpgaconvnet_in_0_V_AWLEN(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWLEN),
    .m_axi_fpgaconvnet_in_0_V_AWSIZE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWSIZE),
    .m_axi_fpgaconvnet_in_0_V_AWBURST(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWBURST),
    .m_axi_fpgaconvnet_in_0_V_AWLOCK(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWLOCK),
    .m_axi_fpgaconvnet_in_0_V_AWCACHE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWCACHE),
    .m_axi_fpgaconvnet_in_0_V_AWPROT(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWPROT),
    .m_axi_fpgaconvnet_in_0_V_AWQOS(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWQOS),
    .m_axi_fpgaconvnet_in_0_V_AWREGION(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWREGION),
    .m_axi_fpgaconvnet_in_0_V_AWUSER(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_AWUSER),
    .m_axi_fpgaconvnet_in_0_V_WVALID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WVALID),
    .m_axi_fpgaconvnet_in_0_V_WREADY(1'b0),
    .m_axi_fpgaconvnet_in_0_V_WDATA(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WDATA),
    .m_axi_fpgaconvnet_in_0_V_WSTRB(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WSTRB),
    .m_axi_fpgaconvnet_in_0_V_WLAST(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WLAST),
    .m_axi_fpgaconvnet_in_0_V_WID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WID),
    .m_axi_fpgaconvnet_in_0_V_WUSER(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_WUSER),
    .m_axi_fpgaconvnet_in_0_V_ARVALID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARVALID),
    .m_axi_fpgaconvnet_in_0_V_ARREADY(fpgaconvnet_port_in_ARREADY),
    .m_axi_fpgaconvnet_in_0_V_ARADDR(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARADDR),
    .m_axi_fpgaconvnet_in_0_V_ARID(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARID),
    .m_axi_fpgaconvnet_in_0_V_ARLEN(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLEN),
    .m_axi_fpgaconvnet_in_0_V_ARSIZE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARSIZE),
    .m_axi_fpgaconvnet_in_0_V_ARBURST(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARBURST),
    .m_axi_fpgaconvnet_in_0_V_ARLOCK(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARLOCK),
    .m_axi_fpgaconvnet_in_0_V_ARCACHE(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARCACHE),
    .m_axi_fpgaconvnet_in_0_V_ARPROT(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARPROT),
    .m_axi_fpgaconvnet_in_0_V_ARQOS(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARQOS),
    .m_axi_fpgaconvnet_in_0_V_ARREGION(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARREGION),
    .m_axi_fpgaconvnet_in_0_V_ARUSER(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_ARUSER),
    .m_axi_fpgaconvnet_in_0_V_RVALID(fpgaconvnet_port_in_RVALID),
    .m_axi_fpgaconvnet_in_0_V_RREADY(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_RREADY),
    .m_axi_fpgaconvnet_in_0_V_RDATA(fpgaconvnet_port_in_RDATA),
    .m_axi_fpgaconvnet_in_0_V_RLAST(fpgaconvnet_port_in_RLAST),
    .m_axi_fpgaconvnet_in_0_V_RID(fpgaconvnet_port_in_RID),
    .m_axi_fpgaconvnet_in_0_V_RUSER(fpgaconvnet_port_in_RUSER),
    .m_axi_fpgaconvnet_in_0_V_RRESP(fpgaconvnet_port_in_RRESP),
    .m_axi_fpgaconvnet_in_0_V_BVALID(1'b0),
    .m_axi_fpgaconvnet_in_0_V_BREADY(Block_proc_U0_m_axi_fpgaconvnet_in_0_V_BREADY),
    .m_axi_fpgaconvnet_in_0_V_BRESP(2'd0),
    .m_axi_fpgaconvnet_in_0_V_BID(1'd0),
    .m_axi_fpgaconvnet_in_0_V_BUSER(1'd0),
    .fpgaconvnet_in_0_V_offset(fpgaconvnet_in_0_V),
    .m_axi_fpgaconvnet_out_0_V_AWVALID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWVALID),
    .m_axi_fpgaconvnet_out_0_V_AWREADY(fpgaconvnet_port_out_AWREADY),
    .m_axi_fpgaconvnet_out_0_V_AWADDR(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWADDR),
    .m_axi_fpgaconvnet_out_0_V_AWID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWID),
    .m_axi_fpgaconvnet_out_0_V_AWLEN(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLEN),
    .m_axi_fpgaconvnet_out_0_V_AWSIZE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWSIZE),
    .m_axi_fpgaconvnet_out_0_V_AWBURST(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWBURST),
    .m_axi_fpgaconvnet_out_0_V_AWLOCK(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWLOCK),
    .m_axi_fpgaconvnet_out_0_V_AWCACHE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWCACHE),
    .m_axi_fpgaconvnet_out_0_V_AWPROT(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWPROT),
    .m_axi_fpgaconvnet_out_0_V_AWQOS(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWQOS),
    .m_axi_fpgaconvnet_out_0_V_AWREGION(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWREGION),
    .m_axi_fpgaconvnet_out_0_V_AWUSER(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_AWUSER),
    .m_axi_fpgaconvnet_out_0_V_WVALID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WVALID),
    .m_axi_fpgaconvnet_out_0_V_WREADY(fpgaconvnet_port_out_WREADY),
    .m_axi_fpgaconvnet_out_0_V_WDATA(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WDATA),
    .m_axi_fpgaconvnet_out_0_V_WSTRB(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WSTRB),
    .m_axi_fpgaconvnet_out_0_V_WLAST(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WLAST),
    .m_axi_fpgaconvnet_out_0_V_WID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WID),
    .m_axi_fpgaconvnet_out_0_V_WUSER(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_WUSER),
    .m_axi_fpgaconvnet_out_0_V_ARVALID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARVALID),
    .m_axi_fpgaconvnet_out_0_V_ARREADY(1'b0),
    .m_axi_fpgaconvnet_out_0_V_ARADDR(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARADDR),
    .m_axi_fpgaconvnet_out_0_V_ARID(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARID),
    .m_axi_fpgaconvnet_out_0_V_ARLEN(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARLEN),
    .m_axi_fpgaconvnet_out_0_V_ARSIZE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARSIZE),
    .m_axi_fpgaconvnet_out_0_V_ARBURST(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARBURST),
    .m_axi_fpgaconvnet_out_0_V_ARLOCK(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARLOCK),
    .m_axi_fpgaconvnet_out_0_V_ARCACHE(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARCACHE),
    .m_axi_fpgaconvnet_out_0_V_ARPROT(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARPROT),
    .m_axi_fpgaconvnet_out_0_V_ARQOS(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARQOS),
    .m_axi_fpgaconvnet_out_0_V_ARREGION(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARREGION),
    .m_axi_fpgaconvnet_out_0_V_ARUSER(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_ARUSER),
    .m_axi_fpgaconvnet_out_0_V_RVALID(1'b0),
    .m_axi_fpgaconvnet_out_0_V_RREADY(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_RREADY),
    .m_axi_fpgaconvnet_out_0_V_RDATA(64'd0),
    .m_axi_fpgaconvnet_out_0_V_RLAST(1'b0),
    .m_axi_fpgaconvnet_out_0_V_RID(1'd0),
    .m_axi_fpgaconvnet_out_0_V_RUSER(1'd0),
    .m_axi_fpgaconvnet_out_0_V_RRESP(2'd0),
    .m_axi_fpgaconvnet_out_0_V_BVALID(fpgaconvnet_port_out_BVALID),
    .m_axi_fpgaconvnet_out_0_V_BREADY(Block_proc_U0_m_axi_fpgaconvnet_out_0_V_BREADY),
    .m_axi_fpgaconvnet_out_0_V_BRESP(fpgaconvnet_port_out_BRESP),
    .m_axi_fpgaconvnet_out_0_V_BID(fpgaconvnet_port_out_BID),
    .m_axi_fpgaconvnet_out_0_V_BUSER(fpgaconvnet_port_out_BUSER),
    .fpgaconvnet_out_0_V_offset(fpgaconvnet_out_0_V),
    .m_axi_fpgaconvnet_wr_0_V_AWVALID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWVALID),
    .m_axi_fpgaconvnet_wr_0_V_AWREADY(1'b0),
    .m_axi_fpgaconvnet_wr_0_V_AWADDR(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWADDR),
    .m_axi_fpgaconvnet_wr_0_V_AWID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWID),
    .m_axi_fpgaconvnet_wr_0_V_AWLEN(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWLEN),
    .m_axi_fpgaconvnet_wr_0_V_AWSIZE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWSIZE),
    .m_axi_fpgaconvnet_wr_0_V_AWBURST(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWBURST),
    .m_axi_fpgaconvnet_wr_0_V_AWLOCK(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWLOCK),
    .m_axi_fpgaconvnet_wr_0_V_AWCACHE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWCACHE),
    .m_axi_fpgaconvnet_wr_0_V_AWPROT(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWPROT),
    .m_axi_fpgaconvnet_wr_0_V_AWQOS(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWQOS),
    .m_axi_fpgaconvnet_wr_0_V_AWREGION(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWREGION),
    .m_axi_fpgaconvnet_wr_0_V_AWUSER(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_AWUSER),
    .m_axi_fpgaconvnet_wr_0_V_WVALID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WVALID),
    .m_axi_fpgaconvnet_wr_0_V_WREADY(1'b0),
    .m_axi_fpgaconvnet_wr_0_V_WDATA(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WDATA),
    .m_axi_fpgaconvnet_wr_0_V_WSTRB(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WSTRB),
    .m_axi_fpgaconvnet_wr_0_V_WLAST(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WLAST),
    .m_axi_fpgaconvnet_wr_0_V_WID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WID),
    .m_axi_fpgaconvnet_wr_0_V_WUSER(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_WUSER),
    .m_axi_fpgaconvnet_wr_0_V_ARVALID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARVALID),
    .m_axi_fpgaconvnet_wr_0_V_ARREADY(fpgaconvnet_port_wr_ARREADY),
    .m_axi_fpgaconvnet_wr_0_V_ARADDR(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARADDR),
    .m_axi_fpgaconvnet_wr_0_V_ARID(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARID),
    .m_axi_fpgaconvnet_wr_0_V_ARLEN(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLEN),
    .m_axi_fpgaconvnet_wr_0_V_ARSIZE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARSIZE),
    .m_axi_fpgaconvnet_wr_0_V_ARBURST(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARBURST),
    .m_axi_fpgaconvnet_wr_0_V_ARLOCK(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARLOCK),
    .m_axi_fpgaconvnet_wr_0_V_ARCACHE(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARCACHE),
    .m_axi_fpgaconvnet_wr_0_V_ARPROT(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARPROT),
    .m_axi_fpgaconvnet_wr_0_V_ARQOS(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARQOS),
    .m_axi_fpgaconvnet_wr_0_V_ARREGION(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARREGION),
    .m_axi_fpgaconvnet_wr_0_V_ARUSER(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_ARUSER),
    .m_axi_fpgaconvnet_wr_0_V_RVALID(fpgaconvnet_port_wr_RVALID),
    .m_axi_fpgaconvnet_wr_0_V_RREADY(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_RREADY),
    .m_axi_fpgaconvnet_wr_0_V_RDATA(fpgaconvnet_port_wr_RDATA),
    .m_axi_fpgaconvnet_wr_0_V_RLAST(fpgaconvnet_port_wr_RLAST),
    .m_axi_fpgaconvnet_wr_0_V_RID(fpgaconvnet_port_wr_RID),
    .m_axi_fpgaconvnet_wr_0_V_RUSER(fpgaconvnet_port_wr_RUSER),
    .m_axi_fpgaconvnet_wr_0_V_RRESP(fpgaconvnet_port_wr_RRESP),
    .m_axi_fpgaconvnet_wr_0_V_BVALID(1'b0),
    .m_axi_fpgaconvnet_wr_0_V_BREADY(Block_proc_U0_m_axi_fpgaconvnet_wr_0_V_BREADY),
    .m_axi_fpgaconvnet_wr_0_V_BRESP(2'd0),
    .m_axi_fpgaconvnet_wr_0_V_BID(1'd0),
    .m_axi_fpgaconvnet_wr_0_V_BUSER(1'd0),
    .fpgaconvnet_wr_0_V_offset(fpgaconvnet_wr_0_V)
);

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = ap_start;

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign ap_done = Block_proc_U0_ap_done;

assign ap_idle = Block_proc_U0_ap_idle;

assign ap_ready = Block_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Block_proc_U0_ap_done;

assign ap_sync_ready = Block_proc_U0_ap_ready;

endmodule //fpgaconvnet_ip
