// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sliding_window (
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        out_V_V1_din,
        out_V_V1_full_n,
        out_V_V1_write,
        out_V_V2_din,
        out_V_V2_full_n,
        out_V_V2_write,
        out_V_V3_din,
        out_V_V3_full_n,
        out_V_V3_write,
        out_V_V4_din,
        out_V_V4_full_n,
        out_V_V4_write,
        out_V_V15_din,
        out_V_V15_full_n,
        out_V_V15_write,
        out_V_V16_din,
        out_V_V16_full_n,
        out_V_V16_write,
        out_V_V17_din,
        out_V_V17_full_n,
        out_V_V17_write,
        out_V_V18_din,
        out_V_V18_full_n,
        out_V_V18_write,
        out_V_V19_din,
        out_V_V19_full_n,
        out_V_V19_write,
        out_V_V210_din,
        out_V_V210_full_n,
        out_V_V210_write,
        out_V_V211_din,
        out_V_V211_full_n,
        out_V_V211_write,
        out_V_V212_din,
        out_V_V212_full_n,
        out_V_V212_write,
        out_V_V213_din,
        out_V_V213_full_n,
        out_V_V213_write,
        out_V_V214_din,
        out_V_V214_full_n,
        out_V_V214_write,
        out_V_V315_din,
        out_V_V315_full_n,
        out_V_V315_write,
        out_V_V316_din,
        out_V_V316_full_n,
        out_V_V316_write,
        out_V_V317_din,
        out_V_V317_full_n,
        out_V_V317_write,
        out_V_V318_din,
        out_V_V318_full_n,
        out_V_V318_write,
        out_V_V319_din,
        out_V_V319_full_n,
        out_V_V319_write,
        out_V_V420_din,
        out_V_V420_full_n,
        out_V_V420_write,
        out_V_V421_din,
        out_V_V421_full_n,
        out_V_V421_write,
        out_V_V422_din,
        out_V_V422_full_n,
        out_V_V422_write,
        out_V_V423_din,
        out_V_V423_full_n,
        out_V_V423_write,
        out_V_V424_din,
        out_V_V424_full_n,
        out_V_V424_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [15:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [15:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
output  [15:0] out_V_V1_din;
input   out_V_V1_full_n;
output   out_V_V1_write;
output  [15:0] out_V_V2_din;
input   out_V_V2_full_n;
output   out_V_V2_write;
output  [15:0] out_V_V3_din;
input   out_V_V3_full_n;
output   out_V_V3_write;
output  [15:0] out_V_V4_din;
input   out_V_V4_full_n;
output   out_V_V4_write;
output  [15:0] out_V_V15_din;
input   out_V_V15_full_n;
output   out_V_V15_write;
output  [15:0] out_V_V16_din;
input   out_V_V16_full_n;
output   out_V_V16_write;
output  [15:0] out_V_V17_din;
input   out_V_V17_full_n;
output   out_V_V17_write;
output  [15:0] out_V_V18_din;
input   out_V_V18_full_n;
output   out_V_V18_write;
output  [15:0] out_V_V19_din;
input   out_V_V19_full_n;
output   out_V_V19_write;
output  [15:0] out_V_V210_din;
input   out_V_V210_full_n;
output   out_V_V210_write;
output  [15:0] out_V_V211_din;
input   out_V_V211_full_n;
output   out_V_V211_write;
output  [15:0] out_V_V212_din;
input   out_V_V212_full_n;
output   out_V_V212_write;
output  [15:0] out_V_V213_din;
input   out_V_V213_full_n;
output   out_V_V213_write;
output  [15:0] out_V_V214_din;
input   out_V_V214_full_n;
output   out_V_V214_write;
output  [15:0] out_V_V315_din;
input   out_V_V315_full_n;
output   out_V_V315_write;
output  [15:0] out_V_V316_din;
input   out_V_V316_full_n;
output   out_V_V316_write;
output  [15:0] out_V_V317_din;
input   out_V_V317_full_n;
output   out_V_V317_write;
output  [15:0] out_V_V318_din;
input   out_V_V318_full_n;
output   out_V_V318_write;
output  [15:0] out_V_V319_din;
input   out_V_V319_full_n;
output   out_V_V319_write;
output  [15:0] out_V_V420_din;
input   out_V_V420_full_n;
output   out_V_V420_write;
output  [15:0] out_V_V421_din;
input   out_V_V421_full_n;
output   out_V_V421_write;
output  [15:0] out_V_V422_din;
input   out_V_V422_full_n;
output   out_V_V422_write;
output  [15:0] out_V_V423_din;
input   out_V_V423_full_n;
output   out_V_V423_write;
output  [15:0] out_V_V424_din;
input   out_V_V424_full_n;
output   out_V_V424_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    sliding_window_line_U0_ap_start;
wire    sliding_window_line_U0_ap_done;
wire    sliding_window_line_U0_ap_continue;
wire    sliding_window_line_U0_ap_idle;
wire    sliding_window_line_U0_ap_ready;
wire    sliding_window_line_U0_in_V_V_read;
wire   [15:0] sliding_window_line_U0_frame_buffer_0_0_V_V_din;
wire    sliding_window_line_U0_frame_buffer_0_0_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_0_1_V_V_din;
wire    sliding_window_line_U0_frame_buffer_0_1_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_0_2_V_V_din;
wire    sliding_window_line_U0_frame_buffer_0_2_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_0_3_V_V_din;
wire    sliding_window_line_U0_frame_buffer_0_3_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_0_4_V_V_din;
wire    sliding_window_line_U0_frame_buffer_0_4_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_1_0_V_V_din;
wire    sliding_window_line_U0_frame_buffer_1_0_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_1_1_V_V_din;
wire    sliding_window_line_U0_frame_buffer_1_1_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_1_2_V_V_din;
wire    sliding_window_line_U0_frame_buffer_1_2_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_1_3_V_V_din;
wire    sliding_window_line_U0_frame_buffer_1_3_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_1_4_V_V_din;
wire    sliding_window_line_U0_frame_buffer_1_4_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_2_0_V_V_din;
wire    sliding_window_line_U0_frame_buffer_2_0_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_2_1_V_V_din;
wire    sliding_window_line_U0_frame_buffer_2_1_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_2_2_V_V_din;
wire    sliding_window_line_U0_frame_buffer_2_2_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_2_3_V_V_din;
wire    sliding_window_line_U0_frame_buffer_2_3_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_2_4_V_V_din;
wire    sliding_window_line_U0_frame_buffer_2_4_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_3_0_V_V_din;
wire    sliding_window_line_U0_frame_buffer_3_0_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_3_1_V_V_din;
wire    sliding_window_line_U0_frame_buffer_3_1_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_3_2_V_V_din;
wire    sliding_window_line_U0_frame_buffer_3_2_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_3_3_V_V_din;
wire    sliding_window_line_U0_frame_buffer_3_3_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_3_4_V_V_din;
wire    sliding_window_line_U0_frame_buffer_3_4_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_4_0_V_V_din;
wire    sliding_window_line_U0_frame_buffer_4_0_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_4_1_V_V_din;
wire    sliding_window_line_U0_frame_buffer_4_1_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_4_2_V_V_din;
wire    sliding_window_line_U0_frame_buffer_4_2_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_4_3_V_V_din;
wire    sliding_window_line_U0_frame_buffer_4_3_V_V_write;
wire   [15:0] sliding_window_line_U0_frame_buffer_4_4_V_V_din;
wire    sliding_window_line_U0_frame_buffer_4_4_V_V_write;
wire    sliding_window_line_U0_start_out;
wire    sliding_window_line_U0_start_write;
wire    sliding_window_out_U0_ap_start;
wire    sliding_window_out_U0_ap_done;
wire    sliding_window_out_U0_ap_continue;
wire    sliding_window_out_U0_ap_idle;
wire    sliding_window_out_U0_ap_ready;
wire    sliding_window_out_U0_frame_buffer_0_0_V_V_read;
wire    sliding_window_out_U0_frame_buffer_0_1_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V_din;
wire    sliding_window_out_U0_out_V_V_write;
wire   [15:0] sliding_window_out_U0_out_V_V1_din;
wire    sliding_window_out_U0_out_V_V1_write;
wire    sliding_window_out_U0_frame_buffer_0_2_V_V_read;
wire    sliding_window_out_U0_frame_buffer_0_3_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2_din;
wire    sliding_window_out_U0_out_V_V2_write;
wire   [15:0] sliding_window_out_U0_out_V_V3_din;
wire    sliding_window_out_U0_out_V_V3_write;
wire    sliding_window_out_U0_frame_buffer_0_4_V_V_read;
wire    sliding_window_out_U0_frame_buffer_1_0_V_V_read;
wire    sliding_window_out_U0_frame_buffer_1_1_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V4_din;
wire    sliding_window_out_U0_out_V_V4_write;
wire   [15:0] sliding_window_out_U0_out_V_V25_din;
wire    sliding_window_out_U0_out_V_V25_write;
wire   [15:0] sliding_window_out_U0_out_V_V255_din;
wire    sliding_window_out_U0_out_V_V255_write;
wire    sliding_window_out_U0_frame_buffer_1_2_V_V_read;
wire    sliding_window_out_U0_frame_buffer_1_3_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V256_din;
wire    sliding_window_out_U0_out_V_V256_write;
wire   [15:0] sliding_window_out_U0_out_V_V257_din;
wire    sliding_window_out_U0_out_V_V257_write;
wire    sliding_window_out_U0_frame_buffer_1_4_V_V_read;
wire    sliding_window_out_U0_frame_buffer_2_0_V_V_read;
wire    sliding_window_out_U0_frame_buffer_2_1_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V258_din;
wire    sliding_window_out_U0_out_V_V258_write;
wire   [15:0] sliding_window_out_U0_out_V_V26_din;
wire    sliding_window_out_U0_out_V_V26_write;
wire   [15:0] sliding_window_out_U0_out_V_V269_din;
wire    sliding_window_out_U0_out_V_V269_write;
wire    sliding_window_out_U0_frame_buffer_2_2_V_V_read;
wire    sliding_window_out_U0_frame_buffer_2_3_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2610_din;
wire    sliding_window_out_U0_out_V_V2610_write;
wire   [15:0] sliding_window_out_U0_out_V_V2611_din;
wire    sliding_window_out_U0_out_V_V2611_write;
wire    sliding_window_out_U0_frame_buffer_2_4_V_V_read;
wire    sliding_window_out_U0_frame_buffer_3_0_V_V_read;
wire    sliding_window_out_U0_frame_buffer_3_1_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2612_din;
wire    sliding_window_out_U0_out_V_V2612_write;
wire   [15:0] sliding_window_out_U0_out_V_V27_din;
wire    sliding_window_out_U0_out_V_V27_write;
wire   [15:0] sliding_window_out_U0_out_V_V2713_din;
wire    sliding_window_out_U0_out_V_V2713_write;
wire    sliding_window_out_U0_frame_buffer_3_2_V_V_read;
wire    sliding_window_out_U0_frame_buffer_3_3_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2714_din;
wire    sliding_window_out_U0_out_V_V2714_write;
wire   [15:0] sliding_window_out_U0_out_V_V2715_din;
wire    sliding_window_out_U0_out_V_V2715_write;
wire    sliding_window_out_U0_frame_buffer_3_4_V_V_read;
wire    sliding_window_out_U0_frame_buffer_4_0_V_V_read;
wire    sliding_window_out_U0_frame_buffer_4_1_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2716_din;
wire    sliding_window_out_U0_out_V_V2716_write;
wire   [15:0] sliding_window_out_U0_out_V_V28_din;
wire    sliding_window_out_U0_out_V_V28_write;
wire   [15:0] sliding_window_out_U0_out_V_V2817_din;
wire    sliding_window_out_U0_out_V_V2817_write;
wire    sliding_window_out_U0_frame_buffer_4_2_V_V_read;
wire    sliding_window_out_U0_frame_buffer_4_3_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2818_din;
wire    sliding_window_out_U0_out_V_V2818_write;
wire   [15:0] sliding_window_out_U0_out_V_V2819_din;
wire    sliding_window_out_U0_out_V_V2819_write;
wire    sliding_window_out_U0_frame_buffer_4_4_V_V_read;
wire   [15:0] sliding_window_out_U0_out_V_V2820_din;
wire    sliding_window_out_U0_out_V_V2820_write;
wire    ap_sync_continue;
wire    frame_buffer_0_0_full_n;
wire   [15:0] frame_buffer_0_0_dout;
wire    frame_buffer_0_0_empty_n;
wire    frame_buffer_0_1_full_n;
wire   [15:0] frame_buffer_0_1_dout;
wire    frame_buffer_0_1_empty_n;
wire    frame_buffer_0_2_full_n;
wire   [15:0] frame_buffer_0_2_dout;
wire    frame_buffer_0_2_empty_n;
wire    frame_buffer_0_3_full_n;
wire   [15:0] frame_buffer_0_3_dout;
wire    frame_buffer_0_3_empty_n;
wire    frame_buffer_0_4_full_n;
wire   [15:0] frame_buffer_0_4_dout;
wire    frame_buffer_0_4_empty_n;
wire    frame_buffer_1_0_full_n;
wire   [15:0] frame_buffer_1_0_dout;
wire    frame_buffer_1_0_empty_n;
wire    frame_buffer_1_1_full_n;
wire   [15:0] frame_buffer_1_1_dout;
wire    frame_buffer_1_1_empty_n;
wire    frame_buffer_1_2_full_n;
wire   [15:0] frame_buffer_1_2_dout;
wire    frame_buffer_1_2_empty_n;
wire    frame_buffer_1_3_full_n;
wire   [15:0] frame_buffer_1_3_dout;
wire    frame_buffer_1_3_empty_n;
wire    frame_buffer_1_4_full_n;
wire   [15:0] frame_buffer_1_4_dout;
wire    frame_buffer_1_4_empty_n;
wire    frame_buffer_2_0_full_n;
wire   [15:0] frame_buffer_2_0_dout;
wire    frame_buffer_2_0_empty_n;
wire    frame_buffer_2_1_full_n;
wire   [15:0] frame_buffer_2_1_dout;
wire    frame_buffer_2_1_empty_n;
wire    frame_buffer_2_2_full_n;
wire   [15:0] frame_buffer_2_2_dout;
wire    frame_buffer_2_2_empty_n;
wire    frame_buffer_2_3_full_n;
wire   [15:0] frame_buffer_2_3_dout;
wire    frame_buffer_2_3_empty_n;
wire    frame_buffer_2_4_full_n;
wire   [15:0] frame_buffer_2_4_dout;
wire    frame_buffer_2_4_empty_n;
wire    frame_buffer_3_0_full_n;
wire   [15:0] frame_buffer_3_0_dout;
wire    frame_buffer_3_0_empty_n;
wire    frame_buffer_3_1_full_n;
wire   [15:0] frame_buffer_3_1_dout;
wire    frame_buffer_3_1_empty_n;
wire    frame_buffer_3_2_full_n;
wire   [15:0] frame_buffer_3_2_dout;
wire    frame_buffer_3_2_empty_n;
wire    frame_buffer_3_3_full_n;
wire   [15:0] frame_buffer_3_3_dout;
wire    frame_buffer_3_3_empty_n;
wire    frame_buffer_3_4_full_n;
wire   [15:0] frame_buffer_3_4_dout;
wire    frame_buffer_3_4_empty_n;
wire    frame_buffer_4_0_full_n;
wire   [15:0] frame_buffer_4_0_dout;
wire    frame_buffer_4_0_empty_n;
wire    frame_buffer_4_1_full_n;
wire   [15:0] frame_buffer_4_1_dout;
wire    frame_buffer_4_1_empty_n;
wire    frame_buffer_4_2_full_n;
wire   [15:0] frame_buffer_4_2_dout;
wire    frame_buffer_4_2_empty_n;
wire    frame_buffer_4_3_full_n;
wire   [15:0] frame_buffer_4_3_dout;
wire    frame_buffer_4_3_empty_n;
wire    frame_buffer_4_4_full_n;
wire   [15:0] frame_buffer_4_4_dout;
wire    frame_buffer_4_4_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_sliding_window_out_U0_din;
wire    start_for_sliding_window_out_U0_full_n;
wire   [0:0] start_for_sliding_window_out_U0_dout;
wire    start_for_sliding_window_out_U0_empty_n;
wire    sliding_window_out_U0_start_full_n;
wire    sliding_window_out_U0_start_write;

sliding_window_line_s sliding_window_line_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sliding_window_line_U0_ap_start),
    .start_full_n(start_for_sliding_window_out_U0_full_n),
    .ap_done(sliding_window_line_U0_ap_done),
    .ap_continue(sliding_window_line_U0_ap_continue),
    .ap_idle(sliding_window_line_U0_ap_idle),
    .ap_ready(sliding_window_line_U0_ap_ready),
    .in_V_V_dout(in_V_V_dout),
    .in_V_V_empty_n(in_V_V_empty_n),
    .in_V_V_read(sliding_window_line_U0_in_V_V_read),
    .frame_buffer_0_0_V_V_din(sliding_window_line_U0_frame_buffer_0_0_V_V_din),
    .frame_buffer_0_0_V_V_full_n(frame_buffer_0_0_full_n),
    .frame_buffer_0_0_V_V_write(sliding_window_line_U0_frame_buffer_0_0_V_V_write),
    .frame_buffer_0_1_V_V_din(sliding_window_line_U0_frame_buffer_0_1_V_V_din),
    .frame_buffer_0_1_V_V_full_n(frame_buffer_0_1_full_n),
    .frame_buffer_0_1_V_V_write(sliding_window_line_U0_frame_buffer_0_1_V_V_write),
    .frame_buffer_0_2_V_V_din(sliding_window_line_U0_frame_buffer_0_2_V_V_din),
    .frame_buffer_0_2_V_V_full_n(frame_buffer_0_2_full_n),
    .frame_buffer_0_2_V_V_write(sliding_window_line_U0_frame_buffer_0_2_V_V_write),
    .frame_buffer_0_3_V_V_din(sliding_window_line_U0_frame_buffer_0_3_V_V_din),
    .frame_buffer_0_3_V_V_full_n(frame_buffer_0_3_full_n),
    .frame_buffer_0_3_V_V_write(sliding_window_line_U0_frame_buffer_0_3_V_V_write),
    .frame_buffer_0_4_V_V_din(sliding_window_line_U0_frame_buffer_0_4_V_V_din),
    .frame_buffer_0_4_V_V_full_n(frame_buffer_0_4_full_n),
    .frame_buffer_0_4_V_V_write(sliding_window_line_U0_frame_buffer_0_4_V_V_write),
    .frame_buffer_1_0_V_V_din(sliding_window_line_U0_frame_buffer_1_0_V_V_din),
    .frame_buffer_1_0_V_V_full_n(frame_buffer_1_0_full_n),
    .frame_buffer_1_0_V_V_write(sliding_window_line_U0_frame_buffer_1_0_V_V_write),
    .frame_buffer_1_1_V_V_din(sliding_window_line_U0_frame_buffer_1_1_V_V_din),
    .frame_buffer_1_1_V_V_full_n(frame_buffer_1_1_full_n),
    .frame_buffer_1_1_V_V_write(sliding_window_line_U0_frame_buffer_1_1_V_V_write),
    .frame_buffer_1_2_V_V_din(sliding_window_line_U0_frame_buffer_1_2_V_V_din),
    .frame_buffer_1_2_V_V_full_n(frame_buffer_1_2_full_n),
    .frame_buffer_1_2_V_V_write(sliding_window_line_U0_frame_buffer_1_2_V_V_write),
    .frame_buffer_1_3_V_V_din(sliding_window_line_U0_frame_buffer_1_3_V_V_din),
    .frame_buffer_1_3_V_V_full_n(frame_buffer_1_3_full_n),
    .frame_buffer_1_3_V_V_write(sliding_window_line_U0_frame_buffer_1_3_V_V_write),
    .frame_buffer_1_4_V_V_din(sliding_window_line_U0_frame_buffer_1_4_V_V_din),
    .frame_buffer_1_4_V_V_full_n(frame_buffer_1_4_full_n),
    .frame_buffer_1_4_V_V_write(sliding_window_line_U0_frame_buffer_1_4_V_V_write),
    .frame_buffer_2_0_V_V_din(sliding_window_line_U0_frame_buffer_2_0_V_V_din),
    .frame_buffer_2_0_V_V_full_n(frame_buffer_2_0_full_n),
    .frame_buffer_2_0_V_V_write(sliding_window_line_U0_frame_buffer_2_0_V_V_write),
    .frame_buffer_2_1_V_V_din(sliding_window_line_U0_frame_buffer_2_1_V_V_din),
    .frame_buffer_2_1_V_V_full_n(frame_buffer_2_1_full_n),
    .frame_buffer_2_1_V_V_write(sliding_window_line_U0_frame_buffer_2_1_V_V_write),
    .frame_buffer_2_2_V_V_din(sliding_window_line_U0_frame_buffer_2_2_V_V_din),
    .frame_buffer_2_2_V_V_full_n(frame_buffer_2_2_full_n),
    .frame_buffer_2_2_V_V_write(sliding_window_line_U0_frame_buffer_2_2_V_V_write),
    .frame_buffer_2_3_V_V_din(sliding_window_line_U0_frame_buffer_2_3_V_V_din),
    .frame_buffer_2_3_V_V_full_n(frame_buffer_2_3_full_n),
    .frame_buffer_2_3_V_V_write(sliding_window_line_U0_frame_buffer_2_3_V_V_write),
    .frame_buffer_2_4_V_V_din(sliding_window_line_U0_frame_buffer_2_4_V_V_din),
    .frame_buffer_2_4_V_V_full_n(frame_buffer_2_4_full_n),
    .frame_buffer_2_4_V_V_write(sliding_window_line_U0_frame_buffer_2_4_V_V_write),
    .frame_buffer_3_0_V_V_din(sliding_window_line_U0_frame_buffer_3_0_V_V_din),
    .frame_buffer_3_0_V_V_full_n(frame_buffer_3_0_full_n),
    .frame_buffer_3_0_V_V_write(sliding_window_line_U0_frame_buffer_3_0_V_V_write),
    .frame_buffer_3_1_V_V_din(sliding_window_line_U0_frame_buffer_3_1_V_V_din),
    .frame_buffer_3_1_V_V_full_n(frame_buffer_3_1_full_n),
    .frame_buffer_3_1_V_V_write(sliding_window_line_U0_frame_buffer_3_1_V_V_write),
    .frame_buffer_3_2_V_V_din(sliding_window_line_U0_frame_buffer_3_2_V_V_din),
    .frame_buffer_3_2_V_V_full_n(frame_buffer_3_2_full_n),
    .frame_buffer_3_2_V_V_write(sliding_window_line_U0_frame_buffer_3_2_V_V_write),
    .frame_buffer_3_3_V_V_din(sliding_window_line_U0_frame_buffer_3_3_V_V_din),
    .frame_buffer_3_3_V_V_full_n(frame_buffer_3_3_full_n),
    .frame_buffer_3_3_V_V_write(sliding_window_line_U0_frame_buffer_3_3_V_V_write),
    .frame_buffer_3_4_V_V_din(sliding_window_line_U0_frame_buffer_3_4_V_V_din),
    .frame_buffer_3_4_V_V_full_n(frame_buffer_3_4_full_n),
    .frame_buffer_3_4_V_V_write(sliding_window_line_U0_frame_buffer_3_4_V_V_write),
    .frame_buffer_4_0_V_V_din(sliding_window_line_U0_frame_buffer_4_0_V_V_din),
    .frame_buffer_4_0_V_V_full_n(frame_buffer_4_0_full_n),
    .frame_buffer_4_0_V_V_write(sliding_window_line_U0_frame_buffer_4_0_V_V_write),
    .frame_buffer_4_1_V_V_din(sliding_window_line_U0_frame_buffer_4_1_V_V_din),
    .frame_buffer_4_1_V_V_full_n(frame_buffer_4_1_full_n),
    .frame_buffer_4_1_V_V_write(sliding_window_line_U0_frame_buffer_4_1_V_V_write),
    .frame_buffer_4_2_V_V_din(sliding_window_line_U0_frame_buffer_4_2_V_V_din),
    .frame_buffer_4_2_V_V_full_n(frame_buffer_4_2_full_n),
    .frame_buffer_4_2_V_V_write(sliding_window_line_U0_frame_buffer_4_2_V_V_write),
    .frame_buffer_4_3_V_V_din(sliding_window_line_U0_frame_buffer_4_3_V_V_din),
    .frame_buffer_4_3_V_V_full_n(frame_buffer_4_3_full_n),
    .frame_buffer_4_3_V_V_write(sliding_window_line_U0_frame_buffer_4_3_V_V_write),
    .frame_buffer_4_4_V_V_din(sliding_window_line_U0_frame_buffer_4_4_V_V_din),
    .frame_buffer_4_4_V_V_full_n(frame_buffer_4_4_full_n),
    .frame_buffer_4_4_V_V_write(sliding_window_line_U0_frame_buffer_4_4_V_V_write),
    .start_out(sliding_window_line_U0_start_out),
    .start_write(sliding_window_line_U0_start_write)
);

sliding_window_out sliding_window_out_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sliding_window_out_U0_ap_start),
    .ap_done(sliding_window_out_U0_ap_done),
    .ap_continue(sliding_window_out_U0_ap_continue),
    .ap_idle(sliding_window_out_U0_ap_idle),
    .ap_ready(sliding_window_out_U0_ap_ready),
    .frame_buffer_0_0_V_V_dout(frame_buffer_0_0_dout),
    .frame_buffer_0_0_V_V_empty_n(frame_buffer_0_0_empty_n),
    .frame_buffer_0_0_V_V_read(sliding_window_out_U0_frame_buffer_0_0_V_V_read),
    .frame_buffer_0_1_V_V_dout(frame_buffer_0_1_dout),
    .frame_buffer_0_1_V_V_empty_n(frame_buffer_0_1_empty_n),
    .frame_buffer_0_1_V_V_read(sliding_window_out_U0_frame_buffer_0_1_V_V_read),
    .out_V_V_din(sliding_window_out_U0_out_V_V_din),
    .out_V_V_full_n(out_V_V_full_n),
    .out_V_V_write(sliding_window_out_U0_out_V_V_write),
    .out_V_V1_din(sliding_window_out_U0_out_V_V1_din),
    .out_V_V1_full_n(out_V_V1_full_n),
    .out_V_V1_write(sliding_window_out_U0_out_V_V1_write),
    .frame_buffer_0_2_V_V_dout(frame_buffer_0_2_dout),
    .frame_buffer_0_2_V_V_empty_n(frame_buffer_0_2_empty_n),
    .frame_buffer_0_2_V_V_read(sliding_window_out_U0_frame_buffer_0_2_V_V_read),
    .frame_buffer_0_3_V_V_dout(frame_buffer_0_3_dout),
    .frame_buffer_0_3_V_V_empty_n(frame_buffer_0_3_empty_n),
    .frame_buffer_0_3_V_V_read(sliding_window_out_U0_frame_buffer_0_3_V_V_read),
    .out_V_V2_din(sliding_window_out_U0_out_V_V2_din),
    .out_V_V2_full_n(out_V_V2_full_n),
    .out_V_V2_write(sliding_window_out_U0_out_V_V2_write),
    .out_V_V3_din(sliding_window_out_U0_out_V_V3_din),
    .out_V_V3_full_n(out_V_V3_full_n),
    .out_V_V3_write(sliding_window_out_U0_out_V_V3_write),
    .frame_buffer_0_4_V_V_dout(frame_buffer_0_4_dout),
    .frame_buffer_0_4_V_V_empty_n(frame_buffer_0_4_empty_n),
    .frame_buffer_0_4_V_V_read(sliding_window_out_U0_frame_buffer_0_4_V_V_read),
    .frame_buffer_1_0_V_V_dout(frame_buffer_1_0_dout),
    .frame_buffer_1_0_V_V_empty_n(frame_buffer_1_0_empty_n),
    .frame_buffer_1_0_V_V_read(sliding_window_out_U0_frame_buffer_1_0_V_V_read),
    .frame_buffer_1_1_V_V_dout(frame_buffer_1_1_dout),
    .frame_buffer_1_1_V_V_empty_n(frame_buffer_1_1_empty_n),
    .frame_buffer_1_1_V_V_read(sliding_window_out_U0_frame_buffer_1_1_V_V_read),
    .out_V_V4_din(sliding_window_out_U0_out_V_V4_din),
    .out_V_V4_full_n(out_V_V4_full_n),
    .out_V_V4_write(sliding_window_out_U0_out_V_V4_write),
    .out_V_V25_din(sliding_window_out_U0_out_V_V25_din),
    .out_V_V25_full_n(out_V_V15_full_n),
    .out_V_V25_write(sliding_window_out_U0_out_V_V25_write),
    .out_V_V255_din(sliding_window_out_U0_out_V_V255_din),
    .out_V_V255_full_n(out_V_V16_full_n),
    .out_V_V255_write(sliding_window_out_U0_out_V_V255_write),
    .frame_buffer_1_2_V_V_dout(frame_buffer_1_2_dout),
    .frame_buffer_1_2_V_V_empty_n(frame_buffer_1_2_empty_n),
    .frame_buffer_1_2_V_V_read(sliding_window_out_U0_frame_buffer_1_2_V_V_read),
    .frame_buffer_1_3_V_V_dout(frame_buffer_1_3_dout),
    .frame_buffer_1_3_V_V_empty_n(frame_buffer_1_3_empty_n),
    .frame_buffer_1_3_V_V_read(sliding_window_out_U0_frame_buffer_1_3_V_V_read),
    .out_V_V256_din(sliding_window_out_U0_out_V_V256_din),
    .out_V_V256_full_n(out_V_V17_full_n),
    .out_V_V256_write(sliding_window_out_U0_out_V_V256_write),
    .out_V_V257_din(sliding_window_out_U0_out_V_V257_din),
    .out_V_V257_full_n(out_V_V18_full_n),
    .out_V_V257_write(sliding_window_out_U0_out_V_V257_write),
    .frame_buffer_1_4_V_V_dout(frame_buffer_1_4_dout),
    .frame_buffer_1_4_V_V_empty_n(frame_buffer_1_4_empty_n),
    .frame_buffer_1_4_V_V_read(sliding_window_out_U0_frame_buffer_1_4_V_V_read),
    .frame_buffer_2_0_V_V_dout(frame_buffer_2_0_dout),
    .frame_buffer_2_0_V_V_empty_n(frame_buffer_2_0_empty_n),
    .frame_buffer_2_0_V_V_read(sliding_window_out_U0_frame_buffer_2_0_V_V_read),
    .frame_buffer_2_1_V_V_dout(frame_buffer_2_1_dout),
    .frame_buffer_2_1_V_V_empty_n(frame_buffer_2_1_empty_n),
    .frame_buffer_2_1_V_V_read(sliding_window_out_U0_frame_buffer_2_1_V_V_read),
    .out_V_V258_din(sliding_window_out_U0_out_V_V258_din),
    .out_V_V258_full_n(out_V_V19_full_n),
    .out_V_V258_write(sliding_window_out_U0_out_V_V258_write),
    .out_V_V26_din(sliding_window_out_U0_out_V_V26_din),
    .out_V_V26_full_n(out_V_V210_full_n),
    .out_V_V26_write(sliding_window_out_U0_out_V_V26_write),
    .out_V_V269_din(sliding_window_out_U0_out_V_V269_din),
    .out_V_V269_full_n(out_V_V211_full_n),
    .out_V_V269_write(sliding_window_out_U0_out_V_V269_write),
    .frame_buffer_2_2_V_V_dout(frame_buffer_2_2_dout),
    .frame_buffer_2_2_V_V_empty_n(frame_buffer_2_2_empty_n),
    .frame_buffer_2_2_V_V_read(sliding_window_out_U0_frame_buffer_2_2_V_V_read),
    .frame_buffer_2_3_V_V_dout(frame_buffer_2_3_dout),
    .frame_buffer_2_3_V_V_empty_n(frame_buffer_2_3_empty_n),
    .frame_buffer_2_3_V_V_read(sliding_window_out_U0_frame_buffer_2_3_V_V_read),
    .out_V_V2610_din(sliding_window_out_U0_out_V_V2610_din),
    .out_V_V2610_full_n(out_V_V212_full_n),
    .out_V_V2610_write(sliding_window_out_U0_out_V_V2610_write),
    .out_V_V2611_din(sliding_window_out_U0_out_V_V2611_din),
    .out_V_V2611_full_n(out_V_V213_full_n),
    .out_V_V2611_write(sliding_window_out_U0_out_V_V2611_write),
    .frame_buffer_2_4_V_V_dout(frame_buffer_2_4_dout),
    .frame_buffer_2_4_V_V_empty_n(frame_buffer_2_4_empty_n),
    .frame_buffer_2_4_V_V_read(sliding_window_out_U0_frame_buffer_2_4_V_V_read),
    .frame_buffer_3_0_V_V_dout(frame_buffer_3_0_dout),
    .frame_buffer_3_0_V_V_empty_n(frame_buffer_3_0_empty_n),
    .frame_buffer_3_0_V_V_read(sliding_window_out_U0_frame_buffer_3_0_V_V_read),
    .frame_buffer_3_1_V_V_dout(frame_buffer_3_1_dout),
    .frame_buffer_3_1_V_V_empty_n(frame_buffer_3_1_empty_n),
    .frame_buffer_3_1_V_V_read(sliding_window_out_U0_frame_buffer_3_1_V_V_read),
    .out_V_V2612_din(sliding_window_out_U0_out_V_V2612_din),
    .out_V_V2612_full_n(out_V_V214_full_n),
    .out_V_V2612_write(sliding_window_out_U0_out_V_V2612_write),
    .out_V_V27_din(sliding_window_out_U0_out_V_V27_din),
    .out_V_V27_full_n(out_V_V315_full_n),
    .out_V_V27_write(sliding_window_out_U0_out_V_V27_write),
    .out_V_V2713_din(sliding_window_out_U0_out_V_V2713_din),
    .out_V_V2713_full_n(out_V_V316_full_n),
    .out_V_V2713_write(sliding_window_out_U0_out_V_V2713_write),
    .frame_buffer_3_2_V_V_dout(frame_buffer_3_2_dout),
    .frame_buffer_3_2_V_V_empty_n(frame_buffer_3_2_empty_n),
    .frame_buffer_3_2_V_V_read(sliding_window_out_U0_frame_buffer_3_2_V_V_read),
    .frame_buffer_3_3_V_V_dout(frame_buffer_3_3_dout),
    .frame_buffer_3_3_V_V_empty_n(frame_buffer_3_3_empty_n),
    .frame_buffer_3_3_V_V_read(sliding_window_out_U0_frame_buffer_3_3_V_V_read),
    .out_V_V2714_din(sliding_window_out_U0_out_V_V2714_din),
    .out_V_V2714_full_n(out_V_V317_full_n),
    .out_V_V2714_write(sliding_window_out_U0_out_V_V2714_write),
    .out_V_V2715_din(sliding_window_out_U0_out_V_V2715_din),
    .out_V_V2715_full_n(out_V_V318_full_n),
    .out_V_V2715_write(sliding_window_out_U0_out_V_V2715_write),
    .frame_buffer_3_4_V_V_dout(frame_buffer_3_4_dout),
    .frame_buffer_3_4_V_V_empty_n(frame_buffer_3_4_empty_n),
    .frame_buffer_3_4_V_V_read(sliding_window_out_U0_frame_buffer_3_4_V_V_read),
    .frame_buffer_4_0_V_V_dout(frame_buffer_4_0_dout),
    .frame_buffer_4_0_V_V_empty_n(frame_buffer_4_0_empty_n),
    .frame_buffer_4_0_V_V_read(sliding_window_out_U0_frame_buffer_4_0_V_V_read),
    .frame_buffer_4_1_V_V_dout(frame_buffer_4_1_dout),
    .frame_buffer_4_1_V_V_empty_n(frame_buffer_4_1_empty_n),
    .frame_buffer_4_1_V_V_read(sliding_window_out_U0_frame_buffer_4_1_V_V_read),
    .out_V_V2716_din(sliding_window_out_U0_out_V_V2716_din),
    .out_V_V2716_full_n(out_V_V319_full_n),
    .out_V_V2716_write(sliding_window_out_U0_out_V_V2716_write),
    .out_V_V28_din(sliding_window_out_U0_out_V_V28_din),
    .out_V_V28_full_n(out_V_V420_full_n),
    .out_V_V28_write(sliding_window_out_U0_out_V_V28_write),
    .out_V_V2817_din(sliding_window_out_U0_out_V_V2817_din),
    .out_V_V2817_full_n(out_V_V421_full_n),
    .out_V_V2817_write(sliding_window_out_U0_out_V_V2817_write),
    .frame_buffer_4_2_V_V_dout(frame_buffer_4_2_dout),
    .frame_buffer_4_2_V_V_empty_n(frame_buffer_4_2_empty_n),
    .frame_buffer_4_2_V_V_read(sliding_window_out_U0_frame_buffer_4_2_V_V_read),
    .frame_buffer_4_3_V_V_dout(frame_buffer_4_3_dout),
    .frame_buffer_4_3_V_V_empty_n(frame_buffer_4_3_empty_n),
    .frame_buffer_4_3_V_V_read(sliding_window_out_U0_frame_buffer_4_3_V_V_read),
    .out_V_V2818_din(sliding_window_out_U0_out_V_V2818_din),
    .out_V_V2818_full_n(out_V_V422_full_n),
    .out_V_V2818_write(sliding_window_out_U0_out_V_V2818_write),
    .out_V_V2819_din(sliding_window_out_U0_out_V_V2819_din),
    .out_V_V2819_full_n(out_V_V423_full_n),
    .out_V_V2819_write(sliding_window_out_U0_out_V_V2819_write),
    .frame_buffer_4_4_V_V_dout(frame_buffer_4_4_dout),
    .frame_buffer_4_4_V_V_empty_n(frame_buffer_4_4_empty_n),
    .frame_buffer_4_4_V_V_read(sliding_window_out_U0_frame_buffer_4_4_V_V_read),
    .out_V_V2820_din(sliding_window_out_U0_out_V_V2820_din),
    .out_V_V2820_full_n(out_V_V424_full_n),
    .out_V_V2820_write(sliding_window_out_U0_out_V_V2820_write)
);

fifo_w16_d2_A frame_buffer_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_0_0_V_V_din),
    .if_full_n(frame_buffer_0_0_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_0_0_V_V_write),
    .if_dout(frame_buffer_0_0_dout),
    .if_empty_n(frame_buffer_0_0_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_0_0_V_V_read)
);

fifo_w16_d2_A frame_buffer_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_0_1_V_V_din),
    .if_full_n(frame_buffer_0_1_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_0_1_V_V_write),
    .if_dout(frame_buffer_0_1_dout),
    .if_empty_n(frame_buffer_0_1_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_0_1_V_V_read)
);

fifo_w16_d2_A frame_buffer_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_0_2_V_V_din),
    .if_full_n(frame_buffer_0_2_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_0_2_V_V_write),
    .if_dout(frame_buffer_0_2_dout),
    .if_empty_n(frame_buffer_0_2_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_0_2_V_V_read)
);

fifo_w16_d2_A frame_buffer_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_0_3_V_V_din),
    .if_full_n(frame_buffer_0_3_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_0_3_V_V_write),
    .if_dout(frame_buffer_0_3_dout),
    .if_empty_n(frame_buffer_0_3_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_0_3_V_V_read)
);

fifo_w16_d2_A frame_buffer_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_0_4_V_V_din),
    .if_full_n(frame_buffer_0_4_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_0_4_V_V_write),
    .if_dout(frame_buffer_0_4_dout),
    .if_empty_n(frame_buffer_0_4_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_0_4_V_V_read)
);

fifo_w16_d2_A frame_buffer_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_1_0_V_V_din),
    .if_full_n(frame_buffer_1_0_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_1_0_V_V_write),
    .if_dout(frame_buffer_1_0_dout),
    .if_empty_n(frame_buffer_1_0_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_1_0_V_V_read)
);

fifo_w16_d2_A frame_buffer_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_1_1_V_V_din),
    .if_full_n(frame_buffer_1_1_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_1_1_V_V_write),
    .if_dout(frame_buffer_1_1_dout),
    .if_empty_n(frame_buffer_1_1_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_1_1_V_V_read)
);

fifo_w16_d2_A frame_buffer_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_1_2_V_V_din),
    .if_full_n(frame_buffer_1_2_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_1_2_V_V_write),
    .if_dout(frame_buffer_1_2_dout),
    .if_empty_n(frame_buffer_1_2_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_1_2_V_V_read)
);

fifo_w16_d2_A frame_buffer_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_1_3_V_V_din),
    .if_full_n(frame_buffer_1_3_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_1_3_V_V_write),
    .if_dout(frame_buffer_1_3_dout),
    .if_empty_n(frame_buffer_1_3_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_1_3_V_V_read)
);

fifo_w16_d2_A frame_buffer_1_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_1_4_V_V_din),
    .if_full_n(frame_buffer_1_4_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_1_4_V_V_write),
    .if_dout(frame_buffer_1_4_dout),
    .if_empty_n(frame_buffer_1_4_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_1_4_V_V_read)
);

fifo_w16_d2_A frame_buffer_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_2_0_V_V_din),
    .if_full_n(frame_buffer_2_0_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_2_0_V_V_write),
    .if_dout(frame_buffer_2_0_dout),
    .if_empty_n(frame_buffer_2_0_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_2_0_V_V_read)
);

fifo_w16_d2_A frame_buffer_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_2_1_V_V_din),
    .if_full_n(frame_buffer_2_1_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_2_1_V_V_write),
    .if_dout(frame_buffer_2_1_dout),
    .if_empty_n(frame_buffer_2_1_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_2_1_V_V_read)
);

fifo_w16_d2_A frame_buffer_2_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_2_2_V_V_din),
    .if_full_n(frame_buffer_2_2_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_2_2_V_V_write),
    .if_dout(frame_buffer_2_2_dout),
    .if_empty_n(frame_buffer_2_2_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_2_2_V_V_read)
);

fifo_w16_d2_A frame_buffer_2_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_2_3_V_V_din),
    .if_full_n(frame_buffer_2_3_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_2_3_V_V_write),
    .if_dout(frame_buffer_2_3_dout),
    .if_empty_n(frame_buffer_2_3_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_2_3_V_V_read)
);

fifo_w16_d2_A frame_buffer_2_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_2_4_V_V_din),
    .if_full_n(frame_buffer_2_4_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_2_4_V_V_write),
    .if_dout(frame_buffer_2_4_dout),
    .if_empty_n(frame_buffer_2_4_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_2_4_V_V_read)
);

fifo_w16_d2_A frame_buffer_3_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_3_0_V_V_din),
    .if_full_n(frame_buffer_3_0_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_3_0_V_V_write),
    .if_dout(frame_buffer_3_0_dout),
    .if_empty_n(frame_buffer_3_0_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_3_0_V_V_read)
);

fifo_w16_d2_A frame_buffer_3_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_3_1_V_V_din),
    .if_full_n(frame_buffer_3_1_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_3_1_V_V_write),
    .if_dout(frame_buffer_3_1_dout),
    .if_empty_n(frame_buffer_3_1_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_3_1_V_V_read)
);

fifo_w16_d2_A frame_buffer_3_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_3_2_V_V_din),
    .if_full_n(frame_buffer_3_2_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_3_2_V_V_write),
    .if_dout(frame_buffer_3_2_dout),
    .if_empty_n(frame_buffer_3_2_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_3_2_V_V_read)
);

fifo_w16_d2_A frame_buffer_3_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_3_3_V_V_din),
    .if_full_n(frame_buffer_3_3_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_3_3_V_V_write),
    .if_dout(frame_buffer_3_3_dout),
    .if_empty_n(frame_buffer_3_3_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_3_3_V_V_read)
);

fifo_w16_d2_A frame_buffer_3_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_3_4_V_V_din),
    .if_full_n(frame_buffer_3_4_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_3_4_V_V_write),
    .if_dout(frame_buffer_3_4_dout),
    .if_empty_n(frame_buffer_3_4_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_3_4_V_V_read)
);

fifo_w16_d2_A frame_buffer_4_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_4_0_V_V_din),
    .if_full_n(frame_buffer_4_0_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_4_0_V_V_write),
    .if_dout(frame_buffer_4_0_dout),
    .if_empty_n(frame_buffer_4_0_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_4_0_V_V_read)
);

fifo_w16_d2_A frame_buffer_4_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_4_1_V_V_din),
    .if_full_n(frame_buffer_4_1_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_4_1_V_V_write),
    .if_dout(frame_buffer_4_1_dout),
    .if_empty_n(frame_buffer_4_1_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_4_1_V_V_read)
);

fifo_w16_d2_A frame_buffer_4_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_4_2_V_V_din),
    .if_full_n(frame_buffer_4_2_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_4_2_V_V_write),
    .if_dout(frame_buffer_4_2_dout),
    .if_empty_n(frame_buffer_4_2_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_4_2_V_V_read)
);

fifo_w16_d2_A frame_buffer_4_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_4_3_V_V_din),
    .if_full_n(frame_buffer_4_3_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_4_3_V_V_write),
    .if_dout(frame_buffer_4_3_dout),
    .if_empty_n(frame_buffer_4_3_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_4_3_V_V_read)
);

fifo_w16_d2_A frame_buffer_4_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(sliding_window_line_U0_frame_buffer_4_4_V_V_din),
    .if_full_n(frame_buffer_4_4_full_n),
    .if_write(sliding_window_line_U0_frame_buffer_4_4_V_V_write),
    .if_dout(frame_buffer_4_4_dout),
    .if_empty_n(frame_buffer_4_4_empty_n),
    .if_read(sliding_window_out_U0_frame_buffer_4_4_V_V_read)
);

start_for_slidingcud start_for_slidingcud_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_sliding_window_out_U0_din),
    .if_full_n(start_for_sliding_window_out_U0_full_n),
    .if_write(sliding_window_line_U0_start_write),
    .if_dout(start_for_sliding_window_out_U0_dout),
    .if_empty_n(start_for_sliding_window_out_U0_empty_n),
    .if_read(sliding_window_out_U0_ap_ready)
);

assign ap_done = sliding_window_out_U0_ap_done;

assign ap_idle = (sliding_window_out_U0_ap_idle & sliding_window_line_U0_ap_idle);

assign ap_ready = sliding_window_line_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = sliding_window_out_U0_ap_done;

assign ap_sync_ready = sliding_window_line_U0_ap_ready;

assign in_V_V_read = sliding_window_line_U0_in_V_V_read;

assign out_V_V15_din = sliding_window_out_U0_out_V_V25_din;

assign out_V_V15_write = sliding_window_out_U0_out_V_V25_write;

assign out_V_V16_din = sliding_window_out_U0_out_V_V255_din;

assign out_V_V16_write = sliding_window_out_U0_out_V_V255_write;

assign out_V_V17_din = sliding_window_out_U0_out_V_V256_din;

assign out_V_V17_write = sliding_window_out_U0_out_V_V256_write;

assign out_V_V18_din = sliding_window_out_U0_out_V_V257_din;

assign out_V_V18_write = sliding_window_out_U0_out_V_V257_write;

assign out_V_V19_din = sliding_window_out_U0_out_V_V258_din;

assign out_V_V19_write = sliding_window_out_U0_out_V_V258_write;

assign out_V_V1_din = sliding_window_out_U0_out_V_V1_din;

assign out_V_V1_write = sliding_window_out_U0_out_V_V1_write;

assign out_V_V210_din = sliding_window_out_U0_out_V_V26_din;

assign out_V_V210_write = sliding_window_out_U0_out_V_V26_write;

assign out_V_V211_din = sliding_window_out_U0_out_V_V269_din;

assign out_V_V211_write = sliding_window_out_U0_out_V_V269_write;

assign out_V_V212_din = sliding_window_out_U0_out_V_V2610_din;

assign out_V_V212_write = sliding_window_out_U0_out_V_V2610_write;

assign out_V_V213_din = sliding_window_out_U0_out_V_V2611_din;

assign out_V_V213_write = sliding_window_out_U0_out_V_V2611_write;

assign out_V_V214_din = sliding_window_out_U0_out_V_V2612_din;

assign out_V_V214_write = sliding_window_out_U0_out_V_V2612_write;

assign out_V_V2_din = sliding_window_out_U0_out_V_V2_din;

assign out_V_V2_write = sliding_window_out_U0_out_V_V2_write;

assign out_V_V315_din = sliding_window_out_U0_out_V_V27_din;

assign out_V_V315_write = sliding_window_out_U0_out_V_V27_write;

assign out_V_V316_din = sliding_window_out_U0_out_V_V2713_din;

assign out_V_V316_write = sliding_window_out_U0_out_V_V2713_write;

assign out_V_V317_din = sliding_window_out_U0_out_V_V2714_din;

assign out_V_V317_write = sliding_window_out_U0_out_V_V2714_write;

assign out_V_V318_din = sliding_window_out_U0_out_V_V2715_din;

assign out_V_V318_write = sliding_window_out_U0_out_V_V2715_write;

assign out_V_V319_din = sliding_window_out_U0_out_V_V2716_din;

assign out_V_V319_write = sliding_window_out_U0_out_V_V2716_write;

assign out_V_V3_din = sliding_window_out_U0_out_V_V3_din;

assign out_V_V3_write = sliding_window_out_U0_out_V_V3_write;

assign out_V_V420_din = sliding_window_out_U0_out_V_V28_din;

assign out_V_V420_write = sliding_window_out_U0_out_V_V28_write;

assign out_V_V421_din = sliding_window_out_U0_out_V_V2817_din;

assign out_V_V421_write = sliding_window_out_U0_out_V_V2817_write;

assign out_V_V422_din = sliding_window_out_U0_out_V_V2818_din;

assign out_V_V422_write = sliding_window_out_U0_out_V_V2818_write;

assign out_V_V423_din = sliding_window_out_U0_out_V_V2819_din;

assign out_V_V423_write = sliding_window_out_U0_out_V_V2819_write;

assign out_V_V424_din = sliding_window_out_U0_out_V_V2820_din;

assign out_V_V424_write = sliding_window_out_U0_out_V_V2820_write;

assign out_V_V4_din = sliding_window_out_U0_out_V_V4_din;

assign out_V_V4_write = sliding_window_out_U0_out_V_V4_write;

assign out_V_V_din = sliding_window_out_U0_out_V_V_din;

assign out_V_V_write = sliding_window_out_U0_out_V_V_write;

assign sliding_window_line_U0_ap_continue = 1'b1;

assign sliding_window_line_U0_ap_start = ap_start;

assign sliding_window_out_U0_ap_continue = ap_continue;

assign sliding_window_out_U0_ap_start = start_for_sliding_window_out_U0_empty_n;

assign sliding_window_out_U0_start_full_n = 1'b1;

assign sliding_window_out_U0_start_write = 1'b0;

assign start_for_sliding_window_out_U0_din = 1'b1;

endmodule //sliding_window
